export const FETCH_DATA = "FETCH_DATA";
export const ADD_UPDATE_ITEM = "ADD_UPDATE_ITEM";
export const CHANGE_VIEW_LIMIT = "CHANGE_VIEW_LIMIT";
export const SEARCH_ITEMS = "SEARCH_ITEMS";
export const NEXT_PREV_ITEMS = "NEXT_PREV_ITEMS";
export const TOGGLE_ACTION_LIST = "TOGGLE_ACTION_LIST";
export const TOGGLE_DELETE_MODAL = "TOGGLE_DELETE_MODAL";
export const FORM_VALIDATION_ERROR = "FORM_VALIDATION_ERROR";
